[package]
name = "wrkflw-evaluator"
version = "0.7.3"
edition.workspace = true
description = "Workflow evaluation functionality for wrkflw execution engine"
license.workspace = true
documentation.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["cli"]
cli = ["colored"]

[dependencies]
# Internal crates
wrkflw-models.workspace = true
wrkflw-validators.workspace = true

# External dependencies
colored = { workspace = true, optional = true }
serde_yaml.workspace = true
